yarnPath: ".yarn/releases/yarn-berry.cjs"

logFilters:
  - code: YN0013
    level: discard
  - code: YN0076
    level: discard
  - code: YN0007
    level: discard

nodeLinker: node-modules

npmRegistryServer: 'https://gitlab.com/api/v4/packages/npm/'